Beth 2048
Ann-Beck/pmm pull request #4
Opened 2024-10-26 02:48 UTC by BethanyJ123

The best ever

2024-10-26 02:52 UTC, ClaraDopler requested changes

2024-10-26 02:52 UTC, ClaraDopler commented on testing/test_app.py
> +def test_app_version_best():
This is stupid fix it

2024-10-26 02:52 UTC, ClaraDopler commented on testing/test_integration.py
> +    This is the best place to do what you want
You don't need this remove it.

2024-10-26 02:52 UTC, ClaraDopler commented on testing/test_module_settings.py
> +
This is point less but I don't care

2024-10-26 02:53 UTC, DelilahMichaels approved these changes
This looks fine to me

2024-10-28 00:59 UTC, ClaraDopler approved these changes
I changed my mind this is OK.

2024-10-28 01:00 UTC, merged